// Code generated by Kitex v0.5.1. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	message "im-demo/kitex_gen/message"
)

func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

var messageServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*message.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{
		"SaveMessage": kitex.NewMethodInfo(saveMessageHandler, newMessageServiceSaveMessageArgs, newMessageServiceSaveMessageResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.1",
		Extra:           extra,
	}
	return svcInfo
}

func saveMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceSaveMessageArgs)
	realResult := result.(*message.MessageServiceSaveMessageResult)
	success, err := handler.(message.MessageService).SaveMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceSaveMessageArgs() interface{} {
	return message.NewMessageServiceSaveMessageArgs()
}

func newMessageServiceSaveMessageResult() interface{} {
	return message.NewMessageServiceSaveMessageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SaveMessage(ctx context.Context, req *message.SaveMsgRequset) (r *message.SaveMsgResponse, err error) {
	var _args message.MessageServiceSaveMessageArgs
	_args.Req = req
	var _result message.MessageServiceSaveMessageResult
	if err = p.c.Call(ctx, "SaveMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
