// Code generated by Kitex v0.5.2. DO NOT EDIT.

package groupservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	group "im-demo/kitex_gen/group"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateGroup(ctx context.Context, req *group.CreateGroupRequest, callOptions ...callopt.Option) (r *group.CommonResponse, err error)
	JoinGroup(ctx context.Context, req *group.JoinGroupRequest, callOptions ...callopt.Option) (r *group.CommonResponse, err error)
	GetGroupMem(ctx context.Context, req *group.GetGroupMemRequest, callOptions ...callopt.Option) (r *group.GetGroupMemResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kGroupServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGroupServiceClient struct {
	*kClient
}

func (p *kGroupServiceClient) CreateGroup(ctx context.Context, req *group.CreateGroupRequest, callOptions ...callopt.Option) (r *group.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateGroup(ctx, req)
}

func (p *kGroupServiceClient) JoinGroup(ctx context.Context, req *group.JoinGroupRequest, callOptions ...callopt.Option) (r *group.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JoinGroup(ctx, req)
}

func (p *kGroupServiceClient) GetGroupMem(ctx context.Context, req *group.GetGroupMemRequest, callOptions ...callopt.Option) (r *group.GetGroupMemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupMem(ctx, req)
}
