// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
	"im-demo/api/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.Cors()}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delfriendMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _wschatMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
	//return nil
}

func _groupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategroupMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _joingroupMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _addfriendMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}
