// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"im-demo/api/initialize"
	"im-demo/api/initialize/rpc"
	"im-demo/api/pkg/kafka"
	"im-demo/api/ws"
)

func main() {
	kafka.InitKafka()
	go kafka.ConsumeMessage(ws.ConsumeKafkaMag)
	r, info := initialize.InitRegistry()
	rpc.Init()
	ws.MyServer = ws.NewServer()
	go ws.MyServer.Start()

	h := server.New(server.WithHostPorts(":8080"),
		server.WithRegistry(r, &info))

	register(h)
	h.Spin()
}
